version=1.0-SNAPSHOT
app.name=opi3

java.source=17
java.target=17

src.dir=src/main/java
res.dir=src/main/resources
web.dir=src/main/webapp

test.src.dir=src/test/java
test.res.dir=src/test/resources
test.maxmemory=512m

build.dir=build/ant
classes.dir=${build.dir}/classes
test.classes.dir=${build.dir}/test-classes

lib.dir=jar/lib

jar.name=${app.name}.jar
war.name=${app.name}.war

main.class=Main

native2ascii.src=src/main/locales
native2ascii.dest=${build.dir}/locales-ascii

env.properties.file=env.properties

plugin.src.dir=src/plugin/java